# Copyright lowRISC contributors.
# Licensed under the Apache License, Version 2.0, see LICENSE for details.
# SPDX-License-Identifier: Apache-2.0

[package]
name = "rom_ext_image"
version = "0.1.0"
authors = ["lowRISC contributors"]
edition = "2018"

[dependencies]
memoffset = "0.6.0"
thiserror = "1.0.24"
zerocopy = "0.5.0"
