# Copyright lowRISC contributors.
# Licensed under the Apache License, Version 2.0, see LICENSE for details.
# SPDX-License-Identifier: Apache-2.0

[package]
name = "rom_ext_signer"
version = "0.1.0"
authors = ["lowRISC contributors"]
edition = "2018"

[profile.dev]
lto = false
opt-level = 2
debug = true

[profile.release]
lto = true
opt-level = 2
debug = true

[dependencies]
anyhow = "1.0.40"
object = "0.25.3"
rom_ext_image = { path = "image" }
thiserror = "1.0.24"
zerocopy = "0.5.0"

# We depend on mundane, but `cargo raze` can't auto generate bazel rules for it.
# In order to not break the current meson-based build system, we'll leave
# mundane as a dependency.  To regenerate the bazel dependency rules via
# `cargo raze`, you'll have to temporarily comment out `mundane`.
[dependencies.mundane]
version = "0.5.0"
features = ["rsa-pkcs1v15"]
